### PR TITLE
fix: support path input from Buffer on many fs APIs

### LINKED ISSUE #292: fs.rmdir looks not support "recursive"
```
fs.rmdir("/some/path", {recursive: true })
```

Will get error
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Buffer
```

### PR DESCRIPTION
**Pull request by 3cp**
There is missing support of `"path <string> | <Buffer> | <URL>"` on many fs APIs.

closes #292

### CODE REVIEW

**Comment by 3cp** [comment]
@tschaub something wrong with your travis account? The CI didn't start.

**Comment by 3cp** [comment]
We can move from travis to github actions (which supports win10 and macOS too), if you want remove the dependency on travis.

File: lib/binding.js [hunk 1]
```diff
@@ -450,6 +450,9 @@ Binding.prototype.stat = function(filepath, options, callback, ctx) {
   markSyscall(ctx, 'stat');
 
   return maybeCallback(wrapStatsCallback(callback), ctx, this, function() {
+    if (Buffer.isBuffer(filepath)) {
+      filepath = filepath.toString();
+    }
```
Comment (sindilevich) [inline lib/binding.js:455]: Suggest refactoring the Buffer stringification out to a utility function. Then, all other places would use the function's result in their code flow.
```suggestion
function stringifyFilepath (filepath) {
    if (Buffer.isBuffer(filepath)) {
      filepath = filepath.toString();
    }
    return filepath || "";
}

...
    // Somewhere else in the code
    pathname = stringifyFilepath(pathname);
```

Comment (3cp) [reply lib/binding.js]: Thx! Refactored. I thought about it, but was lazy :)

Skipped `|| ""` because we want exception to report original user input, not `""` (which will confuse user when debugging their code).

**Comment by tschaub** [comment]
> We can move from travis to github actions (which supports win10 and macOS too), if you wanna remove the dependency on travis.

Good suggestion.  Please rebase now that #296 is in.

**Comment by 3cp** [comment]
Passed checks.

**Comment by tschaub** [comment]
Thanks, @3cp!
